# Chapter 1

## Note #1 - Computational Graphs and Sessions
In Tensorflow, we create the computational graphs first (sort of like blueprints). These computational graphs consists of tensor Objects such as placeholders, constants and variables. They do not have any values associated with them yet. After creating the graphs, we can execute the graph using Session Object. The actual calculations and transfer of information are taken place here. 

In [5]:
import tensorflow as tf

In [6]:
'''
This block is the computational graph that creates two vectors and add them together.
'''
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = v_1 + v_2

In [7]:
'''
Here we create the Session object and evaluate the vector addition.
'''
sess = tf.Session()
print(sess.run(v_add))
sess.close()

[3 3 8 7]


In [8]:
with tf.Session() as sess:
    print(sess.run(v_add)) #advantage of using WITH keyword is that one do no need to close the session

[3 3 8 7]


In [9]:
with tf.Session() as sess:
    print(sess.run([v_1,v_2,v_add])) #we can also run more than one tensor Objects in the session run

[array([1, 2, 3, 4], dtype=int32), array([2, 1, 5, 3], dtype=int32), array([3, 3, 8, 7], dtype=int32)]


The above codes have also demonstrated that we can have many session objects in the same program code.

## Note #2 - InteractiveSession
Instead of using tf.Session(), using tf.InteractiveSession() is more convenient because it makes itself the default session so that tensor Objects can be run directly using eval() method without explicitly calling the session.

In [10]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [11]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])

v_add = tf.add(v_1, v_2) # equivalent to v_1 + v_2

In [12]:
print(v_add.eval()) #there is no need to call session as in the previous exercise
sess.close()

[3 3 8 7]


## Note #3 - Constants

In [13]:
import tensorflow as tf

In [14]:
tf.set_random_seed(43) #seed is used to obtain the same random numbers in multiple runs or sessions

t_1 = tf.constant(4) #scalar constant
t_2 = tf.constant([4,3,2]) #vector constant
t_3 = tf.zeros([2,3], tf.int32) #zero matrix of shape [2,3] with dtype of tf.int32
t_4 = tf.zeros_like(t_2) #creates a zero matrix of same shape as t_2
t_5 = tf.ones_like(t_2) #creates a ones matrix of same shape as t_2
t_6 = tf.linspace(2.0, 5.0, 5) #creates a sequence of evenly spaced numbers from #1 argument to #2 argument within total #3 argument value. The corresponding values differ by (#1 arg - #2 arg)/(#3 arg - 1)
t_7 = tf.range(0, 10 , 1) #generate a sequence of numbers from #1 arg value to #2 arg value (this value is not included) incremented by #3 arg value.
t_8 = tf.random_normal([2,3], mean=2.0, stddev=4) #creates a matrix of shape [2,3] with random values from a normal distribution with the specified mean and s.deviation.
t_9 = tf.truncated_normal([1,5], stddev=2) #creates random values from a truncated normal distribution
t_10= tf.random_uniform([2,3], maxval=4) #creates a random values from a given gsamma distribution
t_11= tf.random_crop(t_9, [2,4]) #randomly crops a given tensor to a specified size
t_12= tf.random_shuffle(t_2) #can be used to shuffle a tensor along its first dimension

## Note #4 - Variables and Placeholders
Every variable has to be initialized. During the initialization, we use constants/random values.

In [15]:
import tensorflow as tf

In [16]:
rand_t = tf.random_uniform([50,50], 0, 10)
var_a = tf.Variable(rand_t)
var_b = tf.Variable(rand_t) #both var_a and var_b will be initialized with random uniform distribution. NOTE that the randomization will be diff since the constant is called twice
var_c = tf.Variable(var_a.initialized_value(), name='var_c') #a variable can also be initialized from another variable

In [ ]:
#THIS BLOCK OF CODE IS NOT MEANT FOR EXECUTION!
#even though we seem to have defined the initialization, we would run into error if we run this block of code.
with tf.Session() as sess:
    print(sess.run(var_b)) 

In tensorflow, we have to explicitly initialize **ALL** declared variables. We do so by :

In [17]:
initial_op = tf.global_variables_initializer() #explicitly initialize the variables
with tf.Session() as sess:
    sess.run(initial_op) #run the initializer
    print(sess.run(var_b)) 

[[3.2807982 0.9483731 6.4560165 ... 7.681868  1.5499115 7.1246347]
 [6.808053  5.982151  1.6034627 ... 9.885722  5.519924  9.597698 ]
 [2.343185  1.4051807 1.030035  ... 1.331507  1.2694907 0.644027 ]
 ...
 [3.726467  3.63001   5.916407  ... 1.2143588 2.585063  6.579155 ]
 [9.83129   2.597053  8.234978  ... 1.8044603 2.7112389 9.690228 ]
 [1.5957212 8.435434  2.742635  ... 5.5689964 7.7261043 9.990404 ]]


In [18]:
with tf.Session() as sess:
    sess.run(var_a.initializer) #each variable can also be separately initialized
    print(sess.run(var_a))

[[3.2807982 0.9483731 6.4560165 ... 7.681868  1.5499115 7.1246347]
 [6.808053  5.982151  1.6034627 ... 9.885722  5.519924  9.597698 ]
 [2.343185  1.4051807 1.030035  ... 1.331507  1.2694907 0.644027 ]
 ...
 [3.726467  3.63001   5.916407  ... 1.2143588 2.585063  6.579155 ]
 [9.83129   2.597053  8.234978  ... 1.8044603 2.7112389 9.690228 ]
 [1.5957212 8.435434  2.742635  ... 5.5689964 7.7261043 9.990404 ]]


Variables can be saved by using the Saver class.

In [ ]:
#THIS BLOCK OF CODE IS NOT MEANT FOR EXECUTION!
saver = tf.train.Saver() #define a saver Operation object
saver.save(sess, "PATH TO SAVE THE MODEL") #save the model in the specified path

Placeholders are used to feed data to the computational graph. When declaring a placeholder, the data type has to be specified.

In [ ]:
#THIS BLOCK OF CODE IS NOT MEANT FOR EXECUTION!
tf.placeholder(dtype, shape=None, name=None) #declaration of a placeholder

In [19]:
x = tf.placeholder("float") #declare a placeholder
y = 2 * x #operation involving the placeholder

data = tf.random_uniform([4,5], 10) #constant
with tf.Session() as sess:
    x_data = sess.run(data) #run the constant
    print(sess.run(y, feed_dict={x:x_data})) #feed the data to the graph with feed_dict

[[ 7.694598   2.1374989  8.848091  17.438251   4.201186 ]
 [ 7.5156755  8.030462  19.753056  16.99377   19.806532 ]
 [18.11021    2.3770256  9.086744   2.817646  11.190812 ]
 [14.517649  10.188196   8.768955   5.226556   2.5024529]]


## Note #5 - Memory optimization

**NOTE** : Constants are stored in the computation graph definition. They are loaded every time the graph is loaded. i.e. They are memory expensive. Variables are stored separately. They can exist on the parameter server.

Therefore, to optimize memory, we can declare constant tensor objects as variables with a trainable flag set to False.

In [20]:
import tensorflow as tf

In [21]:
large_tensor = tf.Variable(tf.ones([9,1,2,3,4]), trainable = False)
converted_to_tensor = tf.convert_to_tensor(large_tensor) #this function converts the given value to tensor type. It accepts Numpy arrays, Python Lists and Python scalars. Converted values can have the functionalities offered by Tensorflow for tensors.

## Note #6 - Matrix Multiplications

In [1]:
import tensorflow as tf

sess = tf.InteractiveSession() #easier to evaluate

In [2]:
X = tf.Variable(tf.eye(10)) #creates a 10 X 10 identity matrix
X.initializer.run() #initialize the variable
print(X.eval())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [3]:
A = tf.Variable(tf.random_normal([5,10])) #shape of A is [5,10]
A.initializer.run()
print(A.eval())

[[-1.2581058  -1.2928249   1.210592    0.90885127  0.32108334  1.235608
   1.0915262  -0.1029485  -0.79255587  0.587188  ]
 [-1.3728172  -0.25091788 -0.3501985   0.9381341  -0.00552434  0.809213
  -1.6306849   1.3454828  -0.98712724 -0.70612895]
 [-2.3624172  -1.1597025  -0.7181455  -0.18346421 -0.37870577  0.4053657
  -0.34864923 -0.8186537  -2.0908263  -0.3720705 ]
 [-0.5587503   0.36042702 -0.2172574  -0.13619396 -0.45643774  1.2256805
   0.16534664 -0.84096736  0.31392846 -1.4535825 ]
 [ 0.26053375 -1.6931767   0.3063439  -0.7508957  -0.49403825  0.089265
   0.88707167  1.220826    0.14635319  0.73631763]]


In [4]:
prod = tf.matmul(A,X) #matrix multiplication between A and X. Since A is 5 X 10 and X is 10 X 10, prod is 5 X 10
print(prod.eval())
# tf.matmul(X,A) would not work because X is 10 X 10 while A is 5 X 10
sess.close()

[[-1.2581058  -1.2928249   1.210592    0.90885127  0.32108334  1.235608
   1.0915262  -0.1029485  -0.79255587  0.587188  ]
 [-1.3728172  -0.25091788 -0.3501985   0.9381341  -0.00552434  0.809213
  -1.6306849   1.3454828  -0.98712724 -0.70612895]
 [-2.3624172  -1.1597025  -0.7181455  -0.18346421 -0.37870577  0.4053657
  -0.34864923 -0.8186537  -2.0908263  -0.3720705 ]
 [-0.5587503   0.36042702 -0.2172574  -0.13619396 -0.45643774  1.2256805
   0.16534664 -0.84096736  0.31392846 -1.4535825 ]
 [ 0.26053375 -1.6931767   0.3063439  -0.7508957  -0.49403825  0.089265
   0.88707167  1.220826    0.14635319  0.73631763]]


In [ ]:
#THIS BLOCK OF CODE IS NOT MEANT FOR EXECUTION!
A = a * b #element-wise multiplication
B = tf.scalar_mul(2, A) #multiplication with a scalar 2
C = tf.div(a,b) #element-wise division
D = tf.mod(a,b) #element-wise remainder of division
tf.cast() # this function is used to convert Tensors from one data type to another

### Tensors

#### NOTE that this section is not from the book. It's merely my own understanding of tensors at the time this was written. 

Tensors are a generalization of matrices. A scalar is 0 rank tensor. Vectors are 1st rank tensors. Matrices are 2nd rank tensors and so on. We can have N-rank tensors. N > 0.

In [22]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [23]:
a = tf.random_uniform([]) #scalar
b = tf.random_uniform([2]) #2-D vector
c = tf.random_uniform([2,3]) # 2x3 matrix
d = tf.random_uniform([3,2,4]) # 3 different sets of 2 x 4 matrices.
e = tf.random_uniform([2,5,3,3]) # 2 different sets of 5 different sets of 3 x 3 matrices.
#I used the word 'sets' knowing that the chances of 2 sets of matrices to have the same values are very low.

a_rank = tf.rank(a)
b_rank = tf.rank(b)
c_rank = tf.rank(c)
d_rank = tf.rank(d)
e_rank = tf.rank(e)

#GET THE VALUES AND THE RANKS
a_val = sess.run(a)
a_rank = sess.run(a_rank)

b_val = sess.run(b)
b_rank = sess.run(b_rank)

c_val = sess.run(c)
c_rank = sess.run(c_rank)

d_val = sess.run(d)
d_rank = sess.run(d_rank)

e_val = sess.run(e)
e_rank = sess.run(e_rank)


print("The rank of a is : ", a_rank, " Shape : ", a_val.shape)
print(a_val)

print("\nThe rank of b is : ", b_rank, " Shape : ", b_val.shape)
print(b_val)

print("\nThe rank of c is : ", c_rank, " Shape : ", c_val.shape)
print(c_val)

print("\nThe rank of d is : ", d_rank, " Shape : ", d_val.shape)
print(d_val)

print("\nThe rank of e is : ", e_rank, " Shape : ", e_val.shape)
print(e_val)

The rank of a is :  0  Shape :  ()
0.60954714

The rank of b is :  1  Shape :  (2,)
[0.86102974 0.80000126]

The rank of c is :  2  Shape :  (2, 3)
[[0.58797777 0.87036157 0.1390984 ]
 [0.7323103  0.7070484  0.9907458 ]]

The rank of d is :  3  Shape :  (3, 2, 4)
[[[0.46372962 0.37517262 0.9685943  0.766507  ]
  [0.6786097  0.00196981 0.88787866 0.62976086]]

 [[0.8082291  0.25542676 0.5268885  0.8240441 ]
  [0.25015485 0.00376654 0.4717554  0.08332086]]

 [[0.9627626  0.4235661  0.53491426 0.99145114]
  [0.5756924  0.25733638 0.58703923 0.8730457 ]]]

The rank of e is :  4  Shape :  (2, 5, 3, 3)
[[[[0.31072533 0.55737185 0.2550944 ]
   [0.49375498 0.535395   0.9172059 ]
   [0.8621429  0.37877798 0.13359714]]

  [[0.7645619  0.4193015  0.43837786]
   [0.5249001  0.15372467 0.68516827]
   [0.83239937 0.50648844 0.27010763]]

  [[0.18647242 0.2247144  0.7674117 ]
   [0.5546135  0.58755445 0.12114131]
   [0.07038653 0.89324117 0.33334148]]

  [[0.9168     0.00561512 0.15711093]
   [0.6270

**Tiling**

tf.tile ()  :This operation creates a new tensor by replicating input multiples times.

In [24]:
import tensorflow as tf
sess = tf.InteractiveSession()

a = tf.random_uniform([2,1,5])
b = tf.tile(a, [1,3,1]) #makes a copy of a at axis 1. i.e. the 1 x 5 matrix will be duplicated 3 times.
#we will now have 2 different sets of 3x5 matrices. NOTE that each of those matrix is duplicated from 2 different 1 x 5 matrices.

val_a = sess.run(a)
val_b = sess.run(b)

print("Original :")
print(val_a)
print("Tiled :")
print("\n",val_b)

Original :
[[[0.02821612 0.24848664 0.71703327 0.70859516 0.29021335]]

 [[0.5872241  0.9671136  0.6879182  0.01659012 0.7272179 ]]]
Tiled :

 [[[0.29671717 0.5724083  0.21955442 0.07671952 0.8188658 ]
  [0.29671717 0.5724083  0.21955442 0.07671952 0.8188658 ]
  [0.29671717 0.5724083  0.21955442 0.07671952 0.8188658 ]]

 [[0.40801263 0.13513625 0.4103371  0.3513304  0.3624152 ]
  [0.40801263 0.13513625 0.4103371  0.3513304  0.3624152 ]
  [0.40801263 0.13513625 0.4103371  0.3513304  0.3624152 ]]]


/home/topiary/nasa/lib/python3.5/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


## Note #7 - Invoking CPU/GPU devices
Tensorflow can be used on multiple devices in one or more computer system. The names of the supported devices recognized by Tensorflow are "/device:CPU:0" , "/device:GPU:0" , "/device:GPU:i" for the i-th GPU device.

In [25]:
import tensorflow as tf

config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True) #this flag is to choose the existing and supported device

In [26]:
with tf.device("/device:GPU:0"): #this operation is done using the first GPU
    rand_t = tf.random_uniform([50,50], 0,10, dtype=tf.float32)
    a = tf.Variable(rand_t)
    b = tf.Variable(rand_t)
    c = tf.matmul(a,b)
    init = tf.global_variables_initializer()

sess = tf.Session(config=config)
sess.run(init)
print(sess.run(c))

[[1524.6902 1155.8137 1315.9207 ... 1313.9629 1500.3273 1523.2443]
 [1180.9535  860.7671 1109.6384 ... 1228.6918 1361.498  1227.9775]
 [1509.1243 1178.2604 1327.1133 ... 1384.2269 1529.2356 1497.7799]
 ...
 [1449.084  1077.0586 1264.3529 ... 1325.5721 1480.0912 1351.4656]
 [1262.6982  976.8368 1205.9143 ... 1203.114  1289.372  1017.9338]
 [1524.532  1184.0737 1374.0588 ... 1483.8293 1639.2434 1464.0505]]
