# Chapter 1

## Note #1 - Computational Graphs and Sessions
In Tensorflow, we create the computational graphs first (sort of like blueprints). These computational graphs consists of tensor Objects such as placeholders, constants and variables. They do not have any values associated with them yet. After creating the graphs, we can execute the graph using Session Object. The actual calculations and transfer of information are taken place here. 

In [8]:
import tensorflow as tf

In [9]:
'''
This block is the computational graph that creates two vectors and add them together.
'''
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])
v_add = v_1 + v_2

In [12]:
'''
Here we create the Session object and evaluate the vector addition.
'''
sess = tf.Session()
print(sess.run(v_add))
sess.close()

[3 3 8 7]


In [13]:
with tf.Session() as sess:
    print(sess.run(v_add)) #advantage of using WITH keyword is that one do no need to close the session

[3 3 8 7]


In [14]:
with tf.Session() as sess:
    print(sess.run([v_1,v_2,v_add])) #we can also run more than one tensor Objects in the session run

[array([1, 2, 3, 4], dtype=int32), array([2, 1, 5, 3], dtype=int32), array([3, 3, 8, 7], dtype=int32)]


The above codes have also demonstrated that we can have many session objects in the same program code.

## Note #2 - InteractiveSession
Instead of using tf.Session(), using tf.InteractiveSession() is more convenient because it makes itself the default session so that tensor Objects can be run directly using eval() method without explicitly calling the session.

In [2]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [4]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])

v_add = tf.add(v_1, v_2) # equivalent to v_1 + v_2

In [5]:
print(v_add.eval()) #there is no need to call session as in the previous exercise
sess.close()

[3 3 8 7]


## Note #3 - Constants

In [6]:
import tensorflow as tf

In [9]:
t_1 = tf.constant(4) #scalar constant
t_2 = tf.constant([4,3,2]) #vector constant
t_3 = tf.zeros([2,3], tf.int32) #zero matrix of shape [2,3] with dtype of tf.int32
t_4 = tf.zeros_like(t_2) #creates a zero matrix of same shape as t_2
t_5 = tf.ones_like(t_2) #creates a ones matrix of same shape as t_2
t_6 = tf.linspace(2.0, 5.0, 5) #creates a sequence of evenly spaced numbers from #1 argument to #2 argument within total #3 argument value. The corresponding values differ by (#1 arg - #2 arg)/(#3 arg - 1)
t_7 = tf.range(0, 10 , 1) #generate a sequence of numbers from #1 arg value to #2 arg value (this value is not included) incremented by #3 arg value.
t_8 = tf.random_normal([2,3], mean=2.0, stddev=4) #creates a matrix of shape [2,3] with random values from a normal distribution with the specified mean and s.deviation.
t_9 = tf.truncated_normal([1,5], stddev=2) #creates random values from a truncated normal distribution
t_10= tf.random_uniform([2,3], maxval=4) #creates a random values from a given gsamma distribution
t_11= tf.random_crop(t_9, [2,4]) 

